apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-agent-deployment
  namespace: genesis
  labels:
    app: genesis-agent
    component: agent-runtime
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: genesis-agent
  template:
    metadata:
      labels:
        app: genesis-agent
        component: agent-runtime
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: genesis-agent-service-account
      containers:
      - name: genesis-agent
        image: genesis-agent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: GENESIS_MODE
          value: "agent"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: genesis-secrets
              key: redis-url
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: genesis-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: genesis-secrets
              key: supabase-anon-key
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: genesis-secrets
              key: gemini-api-key
        - name: PLAYWRIGHT_BROWSERS_PATH
          value: "/ms-playwright"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            ephemeral-storage: "5Gi"
          limits:
            memory: "4Gi"
            cpu: "2000m"
            ephemeral-storage: "10Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: playwright-cache
          mountPath: /ms-playwright
        - name: tmp-volume
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            add:
            - SYS_ADMIN  # Required for browser sandboxing
      volumes:
      - name: workspace
        emptyDir:
          sizeLimit: 5Gi
      - name: playwright-cache
        emptyDir:
          sizeLimit: 2Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - genesis-agent
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "genesis.ai/agent-workload"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: genesis-agent-service
  namespace: genesis
  labels:
    app: genesis-agent
spec:
  selector:
    app: genesis-agent
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: genesis-agent-hpa
  namespace: genesis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: genesis-agent-deployment
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: active_agents
      target:
        type: AverageValue
        averageValue: "10"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60